---
name: Terraform
on:
  push:
    branches:
      - main
  pull_request: null
permissions:
  contents: read
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Azure Credentials
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: |
          ls
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
